### ISSUE TITLE
Add table gcp_iam_workload_identity_pool

### ISSUE THREAD

**Issue by chr-b** [turbot/steampipe-plugin-gcp#377]
**References**
https://cloud.google.com/iam/docs/reference/rest/v1/projects.locations.workloadIdentityPools
https://cloud.google.com/iam/docs/reference/rest/v1/projects.locations.workloadIdentityPools.providers

When adding workload identity pools, the providers that are associated with an identity pool are super useful as well.

A general overview on Workload Identity Pools and providers is available here: https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers

**Comment by misraved** [comment]
Thanks @chr-b, for creating this request with detailed API references 👍 .

I think it is better to create two separate tables based on the APIs and docs that you sent over:
- `gcp_iam_workload_identity_pool`
- `gcp_iam_workload_identity_pool_provider`

If anyone is interested in trying to add these tables, we're always excited to see new PRs coming in! For more information on our coding and documentation standards, please have a look at [Table and Column Standards](https://steampipe.io/docs/develop/standards) and [Table Documentation Standards](https://steampipe.io/docs/develop/table-docs-standards). If you have any questions about the development process otherwise, please let us know!
