### ISSUE TITLE
Add table to list all resources present in a specified project

### ISSUE THREAD

**Issue by Subhajit97** [turbot/steampipe-plugin-gcp#78]
We can list all the resources present in a project.
There is a CLI command `gcloud asset search-all-resources --scope=projects/<project_id or project_number>`

**Comment by johnsmyth** [comment]
We should address the GCP asset service in a more holistic fashion - needs a bit of design...

**Comment by hutchic** [comment]
Was hoping steampipe might include the GCP asset inventory API.

Specific use case for context is monitoroing assets for changes https://cloud.google.com/asset-inventory/docs/monitoring-asset-changes by creating a feed

**Comment by cbruno10** [comment]
Hi @hutchic , I understand you use feeds today, but once you have a feed, how do you use it?

Steampipe tables allow you to get information about resources, e.g., list Compute instances, get information about a specific Storage bucket, but they don't support creating, updating, or deleting resources by design. So through Steampipe, you would not be able to create a feed, but you could list feeds or get information about a specific feed. From the [feeds API](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/feeds), it looks like you can get metadata about a feed, but not pull out the notifications from it.

If you're more looking to get the notifications from a given feed, then another table (new or existing) may be better. For instance, if a feed sends notifications to a Storage bucket, then we could list items from that bucket (this table doesn't exist yet, but could be created).

Are you also looking to list assets/resources through the Cloud Asset service? For instance, do you use the `gcloud asset list` command at all?

**Comment by hutchic** [comment]
I'm trying to address two distinct, yet interrelated use-cases:

- Getting a complete export of all GCP assets. While gcloud asset list and its API can provide this, it consumes more API quota. The asset export option, which is asynchronous, offers a more quota-efficient alternative.
- I want live (near live) updates of changes to GCP assets.

Your point on Steampipe being a fetch-only tool is well taken. Indeed, both of these operations imply resource creation. Yet, I believe there's room to explore how we can leverage these capabilities more optimally within Steampipe's framework. :thinking:
